blank_issues_enabled: false
contact_links:
  - name: Awesome Lithuania FAQ
    url: https://www.awesome-lithuania.com/about/faq
    about: Frequently Asked Questions
  - name: Awesome Lithuania info email
    url: mailto:info@awesome-lithuania.com
    about: Should you have any questions not covered in FAQ, feel free to email us.
